### ISSUE TITLE
Resolves CVX 210 to J&J instead of to Astra Zeneca.

### ISSUE THREAD

**Issue by bradhead** [damaguire/SmartHealthCardScanner#1]
had it scan a QR we have to test and is resolves to ohnson and Johnson instead of to Astra Zeneca when supplying cvx=210.  See QR attache
![download-3](https://user-images.githubusercontent.com/38706615/138358404-052b4b93-94bb-41c3-a7e5-d25b92624d17.jpg)
d.

**Comment by damaguire** [comment]
Apologies for that. Didn't code in a catch for AstraZenica or a few other valid CVX codes (was only focusing on the three I had on hand). 

I just pushed a change that should be live now and has the fix. I'll leave the issue open a little longer just in case something else comes up but it should be good to go.

All the best!

**Comment by bradhead** [comment]
Thanks for the fast fix. Unfortunatley, it only parsed the first of the two vaccines. The first one is actually CoviShield and the second one is Astra Zeneca. Oddly they share the same CVX code... but they don't share the same Snomed-CT code, which our example includes. So annoying.

**Comment by damaguire** [comment]
Huh, that is interesting that they share the same CVX code. The QR you sent me though is parsing two vaccines and both seem to be listed as "ASZ" which I thought is AstraZeneca. Currently I don't parse off of Snomed code but I can add it to my list of fixes to check that as well as CVX. 


<img width="383" alt="Screen Shot 2021-10-21 at 3 26 29 PM" src="https://user-images.githubusercontent.com/20866647/138366013-5b72f204-bafc-4f19-81c6-4b818f89dc45.png">
<img width="282" alt="Screen Shot 2021-10-21 at 3 26 05 PM" src="https://user-images.githubusercontent.com/20866647/138366015-fa2ac7d0-b2fe-4088-a50c-aeacf75dafac.png">

**Comment by damaguire** [comment]
I still don't parse off of SNOMED code but I do parse for AstraZeneca now. CoviShield is listed as an alternate name for AstraZeneca and so it will be reported here as AstraZeneca. I will update later with Pfizer child dose numbers among other new CVX code entries.
